### ISSUE TITLE
outbound call - e164 is not working

### ISSUE THREAD

**Issue by Ash-Garg** [jambonz/sbc-outbound#5] opened 2020-07-15 19:34 UTC
Feature Server is sending the correct e164 formated invite to SBC-outbound, However SBC-outbound is striping the '+' in 'To' header before sending the invite out. 

4|sbc-outbound        | {"level":30, "time": "2020-07-15T17:49:37.352Z","pid":1406,"hostname":"ip-172-31-32-10","callId":"644b806d-4166-1239-00b9-029c09eefeb0","msg":"**received outbound INVITE to sip:+4412345678@cpasstest.sip.provider.com:5060** from server at tcp/172.31.32.10:5060,udp/18.xx.xx.xx:5060","v":1}

4|sbc-outbound        | {"level":30, "time": "2020-07-15T17:49:37.363Z","pid":1406,"hostname":"ip-172-31-32-10","callId":"644b806d-4166-1239-00b9-029c09eefeb0","msg":"**sending INVITE to sip:4412345678@cpasstest.sip.provider.com:5060**","v":1}

**Comment by davehorton** [comment] 2020-07-15 20:01
Yes, the problem is here:

https://github.com/jambonz/sbc-outbound/blob/25c1f11935fb55867482dea643d44f054e01017e/lib/call-session.js#L96

The issue is that to date I have been working with carriers that require E.164 format without the leading plus.  I need to make this configurable on the SIP trunk group level, but I want to make sure to do it thoughtfully.

For now, for your testing, can you just edit that line to remove that logic?

**Comment by Ash-Garg** [comment] 2020-07-15 20:33
Thanks Dave,I commented the whole catch and try block and it has done the trick..!

**Comment by davehorton** [comment] 2020-07-15 23:49
ok great, closing this for now.  Let me know how you get along and feel free to open issues when you are blocked.

**Closed by davehorton** 2020-07-15 23:49 UTC
